$(document).ready(function(){
    $('.cover').click(function(){
        $('.jaihon2').css("opacity","1");
        $('.jaihon1').css("opacity","1");
    })
    $('.jaihon1').click(function(){
        $('.jaihon2').css("opacity","0");
        $('.jaihon1').css("opacity","0");
    })
/*----------------------------------*/
    /*$('.cover1').click(function(){
        $('.weiyang2').css("opacity","1");
        $('.weiyang1').css("opacity","1");
    })
    $('.weiyang1').click(function(){
        $('.weiyang2').css("opacity","0");
        $('.weiyang1').css("opacity","0");
    })*/
})
/*----------------------------------*/

/*----------------------------------*/
